services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    env_file:
      - ./.env  
    command: ["npm", "run", "dev"]
